# Generated by Django 6.0.7 on 2026-08-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sistema', models.CharField(default='Mi Colmena', max_length=100)),
                ('nombre_entidad', models.CharField(blank=True, max_length=150)),
                ('correo_contacto', models.EmailField(blank=True, max_length=254)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20)),
                ('descripcion', models.TextField(blank=True, max_length=500)),
                ('zona_horaria', models.CharField(default='America/Bogota', max_length=50)),
                ('formato_fecha', models.CharField(default='d/m/Y', max_length=20)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del sistema',
                'verbose_name_plural': 'Configuración del sistema',
            },
        ),
    ]
