# Generated by Django 6.0.7 on 2026-08-23 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='formato_fecha',
        ),
        migrations.RemoveField(
            model_name='configuracionsistema',
            name='zona_horaria',
        ),
    ]
