# Generated by Django 6.0.7 on 2026-08-23 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_admin', '0002_remove_configuracionsistema_formato_fecha_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionNotificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activar_notificaciones', models.BooleanField(default=True)),
                ('alertas_colmenas_riesgo', models.BooleanField(default=True)),
                ('alertas_incidencias', models.BooleanField(default=True)),
                ('alertas_mantenimientos', models.BooleanField(default=True)),
                ('alertas_agenda', models.BooleanField(default=True)),
                ('alertas_seguridad', models.BooleanField(default=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de notificaciones',
                'verbose_name_plural': 'Configuración de notificaciones',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('incidencia', 'Incidencia'), ('mantenimiento', 'Mantenimiento'), ('colmena', 'Colmena'), ('agenda', 'Agenda'), ('seguridad', 'Seguridad'), ('sistema', 'Sistema')], default='sistema', max_length=30)),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.TextField(max_length=1000)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
