# Generated by Django 6.0.7 on 2026-08-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_admin', '0003_configuracionnotificaciones_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionnotificaciones',
            name='referencia',
            field=models.CharField(blank=True, db_index=True, default='', max_length=180),
        ),
    ]
