# Generated by Django 6.0.7 on 2026-08-24 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_admin', '0005_remove_configuracionnotificaciones_referencia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlIntentosLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intentos_fallidos', models.PositiveIntegerField(default=0)),
                ('primer_intento', models.DateTimeField(blank=True, null=True)),
                ('ultimo_intento', models.DateTimeField(blank=True, null=True)),
                ('alerta_enviada', models.BooleanField(default=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='control_intentos_login', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Control de intentos de inicio de sesión',
                'verbose_name_plural': 'Controles de intentos de inicio de sesión',
            },
        ),
    ]
