# Generated by Django 6.0.7 on 2026-08-25 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_admin', '0006_controlintentoslogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cerrar_sesion_inactividad', models.BooleanField(default=True)),
                ('minutos_inactividad', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(480)])),
                ('registrar_historial_accesos', models.BooleanField(default=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de seguridad',
                'verbose_name_plural': 'Configuración de seguridad',
            },
        ),
    ]
