# Generated by Django 6.0.7 on 2026-08-26 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel_admin', '0007_configuracionseguridad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ControlIntentosLogin',
        ),
    ]
