# Generated by Django 6.0.7 on 2026-08-26 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_admin', '0008_delete_controlintentoslogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionseguridad',
            name='bloquear_intentos_fallidos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracionseguridad',
            name='intentos_maximos_login',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='configuracionseguridad',
            name='minutos_bloqueo_login',
            field=models.PositiveSmallIntegerField(default=15, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)]),
        ),
    ]
