# Generated by Django 6.0.7 on 2026-08-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_admin', '0009_configuracionseguridad_bloquear_intentos_fallidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionseguridad',
            name='obligar_2fa_administradores',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracionseguridad',
            name='obligar_2fa_todos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracionseguridad',
            name='permitir_2fa',
            field=models.BooleanField(default=True),
        ),
    ]
