# Generated by Django 6.0.7 on 2026-08-25 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, unique=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('navegador', models.CharField(blank=True, max_length=100)),
                ('sistema_operativo', models.CharField(blank=True, max_length=100)),
                ('dispositivo', models.CharField(blank=True, max_length=50)),
                ('user_agent', models.TextField(blank=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('ultima_actividad', models.DateTimeField(auto_now=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('motivo_cierre', models.CharField(blank=True, max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de usuario',
                'verbose_name_plural': 'Sesiones de usuarios',
                'ordering': ['-ultima_actividad'],
            },
        ),
    ]
