# Generated by Django 6.0.7 on 2026-08-26 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('inactividad', 'Cierre por inactividad'), ('cambio_password', 'Cambio de contraseña'), ('cierre_remoto', 'Cierre remoto de sesión'), ('sistema', 'Actividad del sistema')], max_length=30)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('navegador', models.CharField(blank=True, max_length=100)),
                ('sistema_operativo', models.CharField(blank=True, max_length=100)),
                ('dispositivo', models.CharField(blank=True, max_length=50)),
                ('user_agent', models.TextField(blank=True)),
                ('detalle', models.CharField(blank=True, max_length=255)),
                ('exitoso', models.BooleanField(default=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_accesos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de acceso',
                'verbose_name_plural': 'Historial de accesos',
                'ordering': ['-fecha'],
            },
        ),
    ]
