# Generated by Django 6.0.7 on 2026-08-26 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_controlintentoslogin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion2FA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False)),
                ('secreto', models.TextField(blank=True)),
                ('fecha_activacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_2fa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración 2FA',
                'verbose_name_plural': 'Configuraciones 2FA',
            },
        ),
    ]
