# Generated by Django 6.0.7 on 2026-08-26 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_configuracion2fa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracion2fa',
            name='secreto',
        ),
    ]
