# Generated by Django 6.0.4 on 2026-07-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_administrador', models.AutoField(db_column='Id_Administrador', primary_key=True, serialize=False)),
                ('celular', models.CharField(blank=True, db_column='Celular', max_length=20, null=True)),
                ('fecharegistro', models.DateField(blank=True, db_column='FechaRegistro', null=True)),
                ('nivelacceso', models.CharField(blank=True, db_column='NivelAcceso', max_length=50, null=True)),
                ('fotoperfil', models.ImageField(blank=True, db_column='FotoPerfil', null=True, upload_to='usuarios/administradores/')),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Apiario',
            fields=[
                ('id_apiario', models.AutoField(db_column='Id_Apiario', primary_key=True, serialize=False)),
                ('nombreapiario', models.CharField(blank=True, db_column='NombreApiario', max_length=100, null=True)),
                ('cantidadcolmenas', models.IntegerField(blank=True, db_column='CantidadColmenas', null=True)),
                ('estadoapiario', models.CharField(blank=True, db_column='EstadoApiario', max_length=50, null=True)),
                ('fechaeclosionapiario', models.DateField(blank=True, db_column='FechaEclosionApiario', null=True)),
                ('ubicacion', models.CharField(blank=True, db_column='Ubicacion', max_length=150, null=True)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('imagen', models.ImageField(blank=True, db_column='Imagen', null=True, upload_to='apiarios/')),
            ],
            options={
                'db_table': 'apiario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Apicultor',
            fields=[
                ('id_apicultor', models.AutoField(db_column='Id_Apicultor', primary_key=True, serialize=False)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=20, null=True)),
                ('zona_trabajo', models.CharField(blank=True, db_column='Zona_Trabajo', max_length=100, null=True)),
                ('experienciaanios', models.IntegerField(blank=True, db_column='ExperienciaAnios', null=True)),
                ('fotoperfil', models.ImageField(blank=True, db_column='FotoPerfil', null=True, upload_to='usuarios/apicultores/')),
            ],
            options={
                'db_table': 'apicultor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Colmena',
            fields=[
                ('id_colmena', models.AutoField(db_column='Id_Colmena', primary_key=True, serialize=False)),
                ('codigocolmena', models.CharField(blank=True, db_column='CodigoColmena', max_length=50, null=True)),
                ('estadocolmena', models.CharField(blank=True, db_column='EstadoColmena', max_length=50, null=True)),
                ('fecharegistro', models.DateField(blank=True, db_column='FechaRegistro', null=True)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('imagen', models.ImageField(blank=True, db_column='Imagen', null=True, upload_to='colmenas/')),
            ],
            options={
                'db_table': 'colmena',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Costos',
            fields=[
                ('id_costo', models.AutoField(db_column='Id_Costo', primary_key=True, serialize=False)),
                ('costoestimado', models.DecimalField(blank=True, db_column='CostoEstimado', decimal_places=2, max_digits=10, null=True)),
                ('costoreal', models.DecimalField(blank=True, db_column='CostoReal', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'costos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exportacion',
            fields=[
                ('id_exportacion', models.AutoField(db_column='Id_Exportacion', primary_key=True, serialize=False)),
                ('tipoexportacion', models.CharField(blank=True, db_column='TipoExportacion', max_length=100, null=True)),
                ('fechaexportacion', models.DateField(blank=True, db_column='FechaExportacion', null=True)),
                ('formato', models.CharField(blank=True, db_column='Formato', max_length=50, null=True)),
                ('archivogenerado', models.CharField(blank=True, db_column='ArchivoGenerado', max_length=255, null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=50, null=True)),
            ],
            options={
                'db_table': 'exportacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id_incidencia', models.AutoField(db_column='Id_Incidencia', primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, db_column='Titulo', max_length=100, null=True)),
                ('prioridad', models.CharField(blank=True, db_column='Prioridad', max_length=50, null=True)),
                ('fechadeteccion', models.DateField(blank=True, db_column='FechaDeteccion', null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=50, null=True)),
                ('observaciones', models.CharField(blank=True, db_column='Observaciones', max_length=255, null=True)),
            ],
            options={
                'db_table': 'incidencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id_mantenimiento', models.AutoField(db_column='Id_Mantenimiento', primary_key=True, serialize=False)),
                ('entidadmantenimiento', models.CharField(blank=True, db_column='EntidadMantenimiento', max_length=50, null=True)),
                ('tipo', models.CharField(blank=True, db_column='Tipo', max_length=100, null=True)),
                ('fechaejecucion', models.DateField(blank=True, db_column='FechaEjecucion', null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=50, null=True)),
                ('prioridad', models.CharField(blank=True, db_column='Prioridad', max_length=50, null=True)),
                ('observaciones', models.CharField(blank=True, db_column='Observaciones', max_length=255, null=True)),
                ('responsable', models.CharField(blank=True, db_column='Responsable', max_length=100, null=True)),
            ],
            options={
                'db_table': 'mantenimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.AutoField(db_column='Id_Reporte', primary_key=True, serialize=False)),
                ('fechageneracion', models.DateField(blank=True, db_column='FechaGeneracion', null=True)),
                ('tiporeporte', models.CharField(blank=True, db_column='TipoReporte', max_length=100, null=True)),
                ('contenido', models.CharField(blank=True, db_column='Contenido', max_length=255, null=True)),
                ('formato', models.CharField(blank=True, db_column='Formato', max_length=50, null=True)),
            ],
            options={
                'db_table': 'reporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(db_column='Id_Rol', primary_key=True, serialize=False)),
                ('nombrerol', models.CharField(db_column='NombreRol', max_length=50)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
                ('nivelacceso', models.CharField(blank=True, db_column='NivelAcceso', max_length=50, null=True)),
                ('permisos', models.CharField(blank=True, db_column='Permisos', max_length=255, null=True)),
                ('estadoactivo', models.IntegerField(blank=True, db_column='EstadoActivo', null=True)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seguimientoapicola',
            fields=[
                ('id_seguimiento', models.AutoField(db_column='Id_Seguimiento', primary_key=True, serialize=False)),
                ('entidadseguida', models.CharField(blank=True, db_column='EntidadSeguida', max_length=50, null=True)),
                ('fecharegistro', models.DateField(blank=True, db_column='FechaRegistro', null=True)),
                ('tiposeguimiento', models.CharField(blank=True, db_column='TipoSeguimiento', max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
                ('responsable', models.CharField(blank=True, db_column='Responsable', max_length=100, null=True)),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=50, null=True)),
            ],
            options={
                'db_table': 'seguimientoapicola',
                'managed': False,
            },
        ),
    ]
