# Generated by Django 6.0.4 on 2026-07-19 20:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmicolmena', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VinculacionApicultor',
            fields=[
                ('id_vinculacion', models.AutoField(db_column='Id_Vinculacion', primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField(db_column='FechaIngreso')),
                ('lunes', models.BooleanField(db_column='Lunes', default=False)),
                ('martes', models.BooleanField(db_column='Martes', default=False)),
                ('miercoles', models.BooleanField(db_column='Miercoles', default=False)),
                ('jueves', models.BooleanField(db_column='Jueves', default=False)),
                ('viernes', models.BooleanField(db_column='Viernes', default=False)),
                ('sabado', models.BooleanField(db_column='Sabado', default=False)),
                ('domingo', models.BooleanField(db_column='Domingo', default=False)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, db_column='FechaActualizacion')),
                ('apicultor', models.OneToOneField(db_column='Id_Apicultor', on_delete=django.db.models.deletion.CASCADE, related_name='vinculacion_laboral', to='dbmicolmena.apicultor')),
            ],
            options={
                'verbose_name': 'Vinculación del apicultor',
                'verbose_name_plural': 'Vinculaciones de apicultores',
                'db_table': 'vinculacion_apicultor',
            },
        ),
        migrations.CreateModel(
            name='RegistroLaboralMensual',
            fields=[
                ('id_registro_laboral', models.AutoField(db_column='Id_RegistroLaboral', primary_key=True, serialize=False)),
                ('mes_reporte', models.DateField(db_column='MesReporte', help_text='Se almacenará el primer día del mes.')),
                ('dias_trabajados_mes', models.PositiveSmallIntegerField(db_column='DiasTrabajadosMes', default=0, validators=[django.core.validators.MaxValueValidator(31)])),
                ('horas_trabajadas_mes', models.DecimalField(db_column='HorasTrabajadasMes', decimal_places=2, default=0, max_digits=7)),
                ('observaciones', models.TextField(blank=True, db_column='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='FechaRegistro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, db_column='FechaActualizacion')),
                ('apicultor', models.ForeignKey(db_column='Id_Apicultor', on_delete=django.db.models.deletion.CASCADE, related_name='registros_laborales', to='dbmicolmena.apicultor')),
            ],
            options={
                'verbose_name': 'Registro laboral mensual',
                'verbose_name_plural': 'Registros laborales mensuales',
                'db_table': 'registro_laboral_mensual',
                'ordering': ['-mes_reporte'],
                'constraints': [models.UniqueConstraint(fields=('apicultor', 'mes_reporte'), name='uq_apicultor_mes_laboral')],
            },
        ),
    ]
