# Generated by Django 6.0.7 on 2026-07-25 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmicolmena', '0002_crear_registro_laboral'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAgenda',
            fields=[
                ('id_evento', models.AutoField(db_column='Id_Evento', primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='Titulo', max_length=150)),
                ('tipo_evento', models.CharField(choices=[('mantenimiento', 'Mantenimiento'), ('revision', 'Revisión'), ('incidencia', 'Incidencia'), ('evento', 'Evento general')], db_column='TipoEvento', default='evento', max_length=20)),
                ('fecha', models.DateField(db_column='Fecha')),
                ('hora', models.TimeField(db_column='Hora')),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', max_length=500)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], db_column='Estado', default='programado', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, db_column='FechaActualizacion')),
                ('creado_por', models.ForeignKey(blank=True, db_column='CreadoPor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_agenda_creados', to=settings.AUTH_USER_MODEL)),
                ('id_apiario', models.ForeignKey(db_column='Id_Apiario', on_delete=django.db.models.deletion.PROTECT, related_name='eventos_agenda', to='dbmicolmena.apiario')),
                ('id_colmena', models.ForeignKey(blank=True, db_column='Id_Colmena', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_agenda', to='dbmicolmena.colmena')),
                ('responsable', models.ForeignKey(blank=True, db_column='Id_Responsable', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_asignados', to='dbmicolmena.apicultor')),
            ],
            options={
                'verbose_name': 'Evento de agenda',
                'verbose_name_plural': 'Eventos de agenda',
                'db_table': 'evento_agenda',
                'ordering': ['fecha', 'hora'],
            },
        ),
    ]
