# Generated by Django 6.0.7 on 2026-07-26 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmicolmena', '0003_crear_eventos_agenda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialReporte',
            fields=[
                ('id_reporte', models.AutoField(db_column='Id_Reporte', primary_key=True, serialize=False)),
                ('tipo_reporte', models.CharField(choices=[('estado_colmenas', 'Estado de colmenas'), ('incidencias', 'Incidencias'), ('mantenimientos', 'Mantenimientos'), ('actividad_apicultores', 'Actividad de apicultores'), ('actividad_mensual', 'Actividad mensual'), ('comparativo', 'Reporte comparativo')], db_column='TipoReporte', max_length=40)),
                ('titulo', models.CharField(db_column='Titulo', max_length=150)),
                ('formato', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Excel')], db_column='Formato', default='pdf', max_length=10)),
                ('fecha_desde', models.DateField(blank=True, db_column='FechaDesde', null=True)),
                ('fecha_hasta', models.DateField(blank=True, db_column='FechaHasta', null=True)),
                ('filtros_aplicados', models.TextField(blank=True, db_column='FiltrosAplicados')),
                ('total_registros', models.PositiveIntegerField(db_column='TotalRegistros', default=0)),
                ('nombre_archivo', models.CharField(db_column='NombreArchivo', max_length=255)),
                ('archivo', models.FileField(db_column='Archivo', upload_to='reportes/%Y/%m/')),
                ('tamano_bytes', models.PositiveBigIntegerField(db_column='TamanoBytes', default=0)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, db_column='FechaGeneracion')),
                ('usuario', models.ForeignKey(blank=True, db_column='UsuarioId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_generados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de reporte',
                'verbose_name_plural': 'Historial de reportes',
                'db_table': 'historial_reporte',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
