# Generated by Django 6.0.7 on 2026-07-29 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbmicolmena', '0004_crear_historial_reportes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Costos',
        ),
    ]
