# Generated by Django 6.0.7 on 2026-08-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmicolmena', '0005_delete_costos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialreporte',
            name='tipo_reporte',
            field=models.CharField(choices=[('estado_colmenas', 'Estado de colmenas'), ('incidencias', 'Incidencias'), ('mantenimientos', 'Mantenimientos'), ('actividad_apicultores', 'Actividad de apicultores'), ('actividad_mensual', 'Actividad mensual'), ('comparativo', 'Reporte comparativo')], db_column='TipoReporte', max_length=50),
        ),
    ]
