# Generated by Django 6.0.4 on 2026-09-02 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmicolmena', '0006_alter_historialreporte_tipo_reporte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaIncidencia',
            fields=[
                ('id_evidencia', models.AutoField(db_column='Id_Evidencia', primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('problema', 'Evidencia del problema'), ('solucion', 'Evidencia de la solución')], db_column='Tipo', max_length=20)),
                ('imagen', models.ImageField(db_column='Imagen', upload_to='incidencias/evidencias/')),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='FechaRegistro')),
                ('id_incidencia', models.ForeignKey(db_column='Id_Incidencia', on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='dbmicolmena.incidencia')),
                ('subido_por', models.ForeignKey(blank=True, db_column='SubidoPor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_incidencia_subidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'evidencia_incidencia',
                'ordering': ['fecha_registro', 'id_evidencia'],
            },
        ),
    ]
