# Generated by Django 6.0.4 on 2026-09-04 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmicolmena', '0007_evidenciaincidencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaMantenimiento',
            fields=[
                ('id_evidencia', models.AutoField(db_column='Id_Evidencia', primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('antes', 'Antes del mantenimiento'), ('durante', 'Durante el mantenimiento'), ('despues', 'Después del mantenimiento')], db_column='Tipo', max_length=20)),
                ('imagen', models.ImageField(db_column='Imagen', upload_to='mantenimientos/evidencias/')),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=255, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='FechaRegistro')),
                ('id_mantenimiento', models.ForeignKey(db_column='Id_Mantenimiento', on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='dbmicolmena.mantenimiento')),
                ('subido_por', models.ForeignKey(blank=True, db_column='SubidoPor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_mantenimiento_subidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'evidencia_mantenimiento',
                'ordering': ['fecha_registro', 'id_evidencia'],
            },
        ),
    ]
